spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.102/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
  context-path: /sell




#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/ 这个只是配置log文件的输出位置，file 配置log文件的名称和位置两者只需要一个就好了
#  file: /var/log/tomcat/sell.log
#  level:
#    com.zut.sell.LoggerTest: debug